char * stringlst = [
N_("Matte jelly"), N_("Bevels"), N_("Bulging, matte jelly covering"),
N_("Glossy jelly"), N_("Bevels"), N_("Bulging, glossy jelly covering"),
N_("Glossy jelly, backlit"), N_("Bevels"), N_("Bulging, glossy jelly covering; two light sources"),
N_("Metal casting"), N_("Bevels"), N_("Smooth drop-like bevel with metallic finish"),
N_("Motion Blur horizontal"), N_("Blur and Sharpen"), N_("Blur as if the object flies horizontally"),
N_("Motion Blur vertical"), N_("Blur and Sharpen"), N_("Blur as if the object flies vertically"),
N_("Apparition"), N_("Shadows and Glows"), N_("Edges are partly feathered out"),
N_("Feathered edges"), N_("Shadows and Glows"), N_("Edges are feathered out"),
N_("Cutout"), N_("Shadows and Glows"), N_("Drop shadow under the cut-out of the shape"),
N_("Jigsaw piece"), N_("Bevels"), N_("Low, sharp bevel"),
N_("Roughen"), N_("Distort Edges"), N_("Small-scale roughened edges"),
N_("Rubber stamp"), N_("Texture overlays"), N_("Random whiteouts inside"),
N_("Ink bleed"), N_("Imitations"), N_("Inky splotches underneath the object"),
N_("Fire"), N_("Imitations"), N_("Edges of object are on fire"),
N_("Bloom"), N_("Bevels"), N_("Soft, cushion-like bevel with matte highlights"),
N_("Ridged border"), N_("Bevels"), N_("Ridged border with inner bevel"),
N_("Ripple"), N_("Distort Edges"), N_("Horizontal rippling of edges"),
N_("Speckle"), N_("Texture overlays"), N_("Fill object with sparse translucent specks"),
N_("Oil slick"), N_("Texture overlays"), N_("Rainbow-colored semitransparent oily splotches"),
N_("Frost"), N_("Texture overlays"), N_("Flake-like white splotches"),
N_("Leopard fur"), N_("Textures"), N_("Leopard spots (loses object's natural color)"),
N_("Zebra"), N_("Textures"), N_("Irregular vertical dark stripes (loses object's natural color)"),
N_("Clouds"), N_("Texture overlays"), N_("Airy, fluffy, sparse white clouds"),
N_("Sharpen"), N_("Blur and Sharpen"), N_(""),
N_("Sharpen more"), N_("Blur and Sharpen"), N_(""),
N_("Emboss"), N_("Image effects"), N_(""),
N_("Oil painting"), N_("Image effects"), N_("Simulates oil painting style"),
N_("Edge detect"), N_("Emphasize Edges"), N_("Detect color edges in object"),
N_("Horizontal edge detect"), N_("Emphasize Edges"), N_("Detect horizontal color edges in object"),
N_("Vertical edge detect"), N_("Emphasize Edges"), N_("Detect vertical color edges in object"),
N_("Pencil"), N_("Emphasize Edges"), N_("Detect color edges and retrace them in grayscale"),
N_("Blueprint"), N_("Emphasize Edges"), N_("Detect color edges and retrace them in blue"),
N_("Desaturate"), N_("Color"), N_("Render object in black and white"),
N_("Invert"), N_("Color"), N_("Invert colors of object"),
N_("Sepia"), N_("Color"), N_("Render object in warm sepia tones"),
N_("Age"), N_("Color"), N_("Imitate aged photograph"),
N_("Organic"), N_("Textures"), N_("Bulging, knotty, slick 3D surface"),
N_("Barbed wire"), N_("Texture overlays"), N_("Gray bevelled wires with drop shadows"),
N_("Swiss cheese"), N_("Texture overlays"), N_("Random inner-bevel holes"),
N_("Blue cheese"), N_("Texture overlays"), N_("Marble-like bluish speckles"),
N_("Button"), N_("Bevels"), N_("Soft bevel, slightly depressed middle"),
N_("Inset"), N_("Shadows and Glows"), N_("Shadowy outer bevel"),
N_("Dripping"), N_("Dripping"), N_("Random paint streaks downwards"),
N_("Wetworks"), N_("Dripping"), N_("Random paint streaks and splotches with 3D relief"),
N_("Electric arc"), N_("Imitations"), N_("Roughened edge stroke with a glow"),
N_("Rainbow melt"), N_("Textures"), N_("Vertical rainbow stripes, edged by splotches with 3D relief"),
N_("Crumpled plastic"), N_("Textures"), N_("Crumpled matte plastic, with melted edge"),
N_("Jam spread"), N_("Textures"), N_("Glossy clumpy jam spread"),
N_("Gold splatter"), N_("Textures"), N_("Splattered cast metal, with golden highlights"),
];
